server:
  port: 8081
spring:
  application:
    name: module_two_sprint_six_gradle
springdoc:
  swagger-ui:
    enabled: true
    tryItOutEnabled: true
    persistAuthorization: true
paymentservice:
  game-mode: false  #Игровой режим
  current-user:
    user-id: 1
    balance: 50000






