spring:
  application:
    name: module_two_sprint_five_gradle
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_USER:practicum_user}
    username: ${POSTGRES_USER:practicum_user}
    password: ${POSTGRES_PASSWORD:mysecretpassword}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
images.path: images/
