server:
  port: 8081
spring:
  application:
    name: module_two_sprint_six_gradle
springdoc:
  swagger-ui:
    enabled: true
    tryItOutEnabled: true
    persistAuthorization: true
paymentservice:
  currentuser:
    userid: 1
    balance: 50000
  overheaded:
    userid: 2
  unavialable:
    userid: 3