spring:
  main:
    web-application-type: reactive
  application:
    name: module_two_sprint_six_gradle
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:practicum_db}
    username: ${POSTGRES_USER:practicum_user}
    password: ${POSTGRES_PASSWORD:mysecretpassword}
    pool:
      enabled: true                               # Включение пула соединений
      initial-size: 10                            # Начальное количество соединений в пуле
      max-size: 50                                # Максимальное количество соединений
      max-idle-time: 30s                          # Время бездействия соединения перед закрытием
      max-life-time: 10m                          # Максимальное время жизни соединения
      validation-query: SELECT 1
  liquibase:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:practicum_db}
    user: ${POSTGRES_USER:practicum_user}
    password: ${POSTGRES_PASSWORD:mysecretpassword}
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:127.0.0.1}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  cache:
    redis:
      time-to-live: PT60M
payment_service_url: ${PAYMENT_SERVICE_URL:http://localhost:8081}
images.path: images/

logging:
  level:
    org.springframework.data.*.*: trace
    org.springframework.cache.*: trace



#driver-class-name: org.postgresql.Driver
