version: "3.9"

services:
  gw:
    image: nginx:latest
    container_name: yp-gateway
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx-practicum-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - yp-shop
      - keycloak

  ngrok:
    image: ngrok/ngrok:latest
    container_name: yp-ngrok
    command: >
      http
      --domain=pseudovelar-fumeless-sung.ngrok-free.dev
      gw:80
    environment:
      NGROK_AUTHTOKEN: 37U6pkF802my2QMVX9Bts01W7Ol_4BZH2YKJQXRhXwRMRU7mc
    depends_on:
      - gw

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_HTTP_ENABLED: "true"
      KC_PROXY: edge
      KC_PROXY_HEADERS: xforwarded
  
    volumes:
      - ./keycloak/realm-demo.json:/opt/keycloak/data/import/realm-demo.json:ro
      - keycloak-data:/opt/keycloak/data
    healthcheck:
      test: ["CMD-SHELL", "echo > /dev/tcp/localhost/8080"]
      interval: 5s
      timeout: 3s
      retries: 20

  postgres:
    image: postgres:18.1
    container_name: yp-postgres
    restart: always
    environment:
      POSTGRES_DB: practicum_db
      POSTGRES_USER: practicum_user
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - db-data:/var/lib/postgresql/18/docker

  redis:
    image: redis:7.4
    container_name: yp-redis
    restart: always
    command: ["redis-server", "--appendonly", "no"]

  yp-payment:
    container_name: yp-payment
    build:
      context: ./ShopPayment
      dockerfile: Dockerfile
    image: yp-payment
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KEYCLOAK_ISSUER_URI: https://pseudovelar-fumeless-sung.ngrok-free.dev/realms/demo-realm	
    depends_on:
      keycloak:
        condition: service_healthy

  yp-shop:
    container_name: yp-shop
    build:
      context: ./ShopCatalogue
      dockerfile: Dockerfile
    image: yp-shop
    restart: on-failure
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      POSTGRES_DB: practicum_db
      POSTGRES_USER: practicum_user
      POSTGRES_PASSWORD: mysecretpassword
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: docker
      PAYMENT_SERVICE_URL: http://yp-payment:8082
      KEYCLOAK_ISSUER_URI: https://pseudovelar-fumeless-sung.ngrok-free.dev/realms/demo-realm
    ports:
      - "8081:8081"
    depends_on:
      keycloak:
        condition: service_healthy
      yp-payment:
        condition: service_started
      postgres:
        condition: service_started
      redis:
        condition: service_started
volumes:
  db-data:
  keycloak-data: