spring:
  application:
    name: module_two_sprint_six_gradle
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_USER:practicum_user}
    username: ${POSTGRES_USER:practicum_user}
    password: ${POSTGRES_PASSWORD:mysecretpassword}
    pool:
      enabled: true                               # Включение пула соединений
      initial-size: 10                            # Начальное количество соединений в пуле
      max-size: 50                                # Максимальное количество соединений
      max-idle-time: 30s                          # Время бездействия соединения перед закрытием
      max-life-time: 10m                          # Максимальное время жизни соединения
      validation-query: SELECT 1
  liquibase:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_USER:practicum_user}
    user: ${POSTGRES_USER:practicum_user}
    password: ${POSTGRES_PASSWORD:mysecretpassword}
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
images.path: images/



#driver-class-name: org.postgresql.Driver
