version: '3.8'

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  # описание контейнера db
  db:
    container_name: db
    # образ, из которого должен быть запущен контейнер
    image: postgres:17.5
    restart: always
    # переменные окружения
    environment:
      - POSTGRES_USER=practicum_user
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=practicum_db
    # volume и связанная с ним директория в контейнере
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    restart: on-failure
    environment:
      - POSTGRES_USER=practicum_user
      - POSTGRES_PASSWORD=mysecretpassword
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=practicum_db
    depends_on:
      - db

  gw:
    container_name: gw
    image: nginx:1.29.0-perl
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx-practicum-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

volumes:
  db-data: